### ISSUE TITLE
Connection value appears as 0.0 figure

### ISSUE THREAD

**Issue by wingZero21** [sebest/collectd-mongodb#12]
Hi,

Added this plugin and the data seems to be coming in for this, however noticed on the connection value its bringing back 00.1 as the figure, not sure how you can have 00.5 of a connection I would have thought this would be a total any ideas?

Details:
[{"target": "mongodb-01.livemongo001_live_dc1_server.mongo.27017.connections.connections.value", "datapoints": [[0.0, 1398867120], [0.0, 1398867180], [0.0, 1398867240], [0.0, 1398867300], [null, 1398867360]]}, {"target": "mongodb-01.livemongo002_live_dc1_server.mongo.27017.connections.connections.value", "datapoints": [[0.0, 1398867120], [0.0, 1398867180], [0.016664999999999999, 1398867240], [0.0, 1398867300], [null, 1398867360]]}, {"target": "mongodb-01.livemongo003_live_dc1_server.mongo.27017.connections.connections.value", "datapoints": [[0.0, 1398867120], [0.016667999999999999, 1398867180], [0.016664000000000002, 1398867240], [0.0, 1398867300], [null, 1398867360]]}, {"target": "mongodb-01.livemongo004_live_dc2_server.mongo.27017.connections.connections.value", "datapoints": [[0.0, 1398867120], [0.016667000000000001, 1398867180], [0.0, 1398867240], [0.0, 1398867300], [0.0, 1398867360]]}, {"target": "mongodb-01.livemongo005_live_dc2_server.mongo.27017.connections.connections.value", "datapoints": [[0.0, 1398867120], [0.0, 1398867180], [0.0, 1398867240], [0.0, 1398867300], [0.0, 1398867360]]}]

**Comment by sebest** [comment]
Any more informations about this one?
Feel free to reopen this issue.
