### ISSUE TITLE
Strange error when loading collectd

### ISSUE THREAD

**Issue by danfinn** [sebest/collectd-mongodb#16]
I added mongodb.py to my collectd.conf file as shown here and it actually appears to be working but I am a bit concerned about this error I get when starting collectd.  I did install mogodb.py in a different location than the one in the example, it's at /etc/collectd.d/mongodb.py.  Here's the error:

[root@mongo6 collectd]# /etc/init.d/collectd restart
Stopping collectd:                                         [  OK  ]
Starting collectd: Parse error in file `/etc/collectd.d/mongodb.py', line 1301 near `<newline>': syntax error, unexpected EOL
yyparse returned error #1
configfile: Cannot read file `/etc/collectd.d/mongodb.py'.
Parse error in file `/etc/collectd.d/mongodb.pyc', line 1318 near `>': syntax error, unexpected CLOSEBRAC
yyparse returned error #1
configfile: Cannot read file `/etc/collectd.d/mongodb.pyc'.
.():():.=.=.=.=[,].=.=.=.=.=.=(,,,,=)::='%-%'%(.,):=(.)=.()[  OK  ]=.=[,].()():=(=.,=.,=)=[.[]]..:.(.,.)=.('')=['']=()

So you can see that it starts and it does appear to be working as I have stats (that I don't quite trust because of the error) in graphite.  Any ideas what's going on here?

system info:

[root@mongo6 collectd]# cat /etc/issue
Amazon Linux AMI release 2014.09
Kernel \r on an \m

[root@mongo6 collectd]# uname -a
Linux mongo6 3.10.42-52.145.amzn1.x86_64 #1 SMP Tue Jun 10 23:46:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

[root@mongo6 collectd]# rpm -q python
python-2.6-2.26.amzn1.noarch

[root@mongo6 collectd]# rpm -q collectd
collectd-5.4.1-1.5.amzn1.x86_64

[root@mongo6 collectd]# rpm -qa|grep -i mongo
mongodb-org-mongos-2.6.5-1.x86_64
mongodb-org-shell-2.6.5-1.x86_64
mongodb-org-tools-2.6.5-1.x86_64
mongodb-org-server-2.6.5-1.x86_64
mongodb-org-2.6.5-1.x86_64

**Comment by danfinn** [comment]
after letting it run for a while and checking graphite it seems like most of the stats are 0 so it's not working so well

**Comment by sebest** [comment]
Are you sure that /etc/collectd.d/mongodb.py was a valid python file?
