### ISSUE TITLE
not compatible with latest pymongo

### ISSUE THREAD

**Issue by vjprasanth** [sebest/collectd-mongodb#18]
Plugin is not compatible with pymongo 3.0 + as the only way to connect to mongo database is using MongoClient not by Connection(which is removed in 3.0 + ). And the link which is provided to install pymongo in documentation point to the master branch which is 3.0.1 version

**Comment by sebest** [comment]
Thanx @vjprasanth , i added a not in the README that pymongo 3.x is not supported.
