### ISSUE TITLE
cannot import name Connection

### ISSUE THREAD

**Issue by rodriguezsergio** [sebest/collectd-mongodb#22]
I think I have everything configured correctly, but I had to add the following line to my config, or so I thought.

```
ModulePath "/usr/local/lib64/python2.6/site-packages/pymongo"
```

In /var/log/messages I see
```
python plugin: Error importing module "mongodb".
Unhandled python exception in importing module: ImportError: cannot import name Connection
```
I initially tried by just including the path to the plugin itself, but that was also failing with

```
Unhandled python exception in importing module: ImportError: No module named pymongo
```
Any ideas what I might be missing?

**Comment by sebest** [comment]
ModulePath should be the path to the mongodb.py from collectd-mongodb not the path to pymongo
You can copy mongodb.py into /opt/collectd-plugins/mongodb.py
And then define ModulePath like this:
    ModulePath "/opt/collectd-plugins/"

**Comment by rodriguezsergio** [comment]
I did pass in the path to the plugin and it still failed.

**Comment by sebest** [comment]
Is it always the exact same error? Did you check that the unix rights are ok (if collectd is not running as root)

**Comment by sebest** [comment]
Oh i think that the problem might be the version of pymongo that you are using, could you upgrade it?

**Comment by sebest** [comment]
if you have this error: "cannot import name Connection" it means that collectd finds the mongodb.py plugin but the mongodb.py plugin does not find pymongo

**Comment by rodriguezsergio** [comment]
Running as root and it's the latest version.

**Comment by rodriguezsergio** [comment]
Weird. I installed into the system python as well and still no dice. Is there a way to see what path collectd is using for python?

**Comment by sebest** [comment]
Maybe adding some debug by printing sys.path or writting it in a file before the import

--
Sebastien E.

**Comment by rodriguezsergio** [comment]
I'm surprised I missed this. The latest pymongo very clearly does not have `Connection.py`.

**Comment by sebest** [comment]
I did a fix that should be backward compatible from pymongo 2.4.x up to the last version.

Could you test it and report any success?

the code is in this branch: https://github.com/sebest/collectd-mongodb/tree/pymongo_3x

thanx!

**Comment by rodriguezsergio** [comment]
Works on my end. :+1:

**Comment by sebest** [comment]
thanx for testing
