### ISSUE TITLE
Should connections be of type "gauge" instead of "counter" ?

### ISSUE THREAD

**Issue by rodriguezsergio** [sebest/collectd-mongodb#24]
For available, current, and total connections, I get 0 unless I change `connections` to `value:GAUGE:0:U`. This is happening in collectd 5.4.1. Not sure how the behavior is in version 4.

Once I make the switch, I see the correct values reflected from `db.serverStatus()` now being stored in graphite.

**Comment by lglayal** [comment]
'connections' name is already used in default collectd types.db and defined as COUNTER. So a new name should be used like 'mongo_connections' to avoid conflict

**Comment by rodriguezsergio** [comment]
That's exactly what I named it in my `types.db`. :stuck_out_tongue:
